# Generated by Django 6.0.4 on 2026-05-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Organisation',
        ),
    ]
