# Generated by Django 6.0.4 on 2026-05-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
