# Generated by Django 6.0.4 on 2026-05-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_rename_organization_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='websites',
            new_name='website',
        ),
    ]
