# Generated by Django 6.0.4 on 2026-05-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_rename_websites_organisation_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='created_At',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='updated_At',
            new_name='updated_at',
        ),
    ]
