# Generated by Django 6.0.4 on 2026-05-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_alter_organisation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='industry',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
