# Generated by Django 6.0.4 on 2026-05-06 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_alter_organisation_industry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ORGANIZATION_CREATED', 'Organization Created'), ('USER_INVITED', 'User Invited'), ('USER_JOINED', 'User Joined'), ('ROLE_CHANGED', 'Role Changed'), ('USER_DEACTIVATED', 'User Deactivated'), ('TICKET_CREATED', 'Ticket Created'), ('TICKET_ASSIGNED', 'Ticket Assigned'), ('TICKET_STARTED', 'Ticket Started'), ('TICKET_RESOLVED', 'Ticket Resolved'), ('TICKET_CLOSED', 'Ticket Closed'), ('COMMENT_ADDED', 'Comment Added'), ('ATTACHMENT_UPLOADED', 'Attachment Uploaded')], max_length=50)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organisations.organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
